### ISSUE TITLE
update freedesktop runtime to 20.08

### ISSUE THREAD

**Issue by eszlari** [flathub/com.tutanota.Tutanota#14]

**Comment by ccptr** [comment]
Could this be reopened? It was reverted in #32 with no explanation. Also see #29.

**Comment by charlag** [comment]
@ccptr This was a mistake, we will fix it with one of the next releases

**Comment by TheEvilSkeleton** [comment]
...I just opened an MR after seeing this issue https://github.com/flathub/com.tutanota.Tutanota/pull/46. Sorry.

**Comment by ccptr** [comment]
What are you sorry for? You're not the one who changed it back to 19.08. Actually you're the one who updated it when it was reverted last time. Thanks for the PR :)

**Comment by TheEvilSkeleton** [comment]
Thank you for the support. The maintainer said that they'll fix it in the next release, which I completely missed it.

**Comment by ccptr** [comment]
It was changed back to 19.08 in #47...

**Comment by TheEvilSkeleton** [comment]
@charlag why do you keep changing the runtime back to 19.08?

**Comment by TheEvilSkeleton** [comment]
Great...
