### ISSUE TITLE
Tutanota crashes very often

### ISSUE THREAD

**Issue by LaPeste** [flathub/com.tutanota.Tutanota#141]
The desktop application crashes from time to time. Nothing specifically is done, I receive a desktop notification (email received or calendar event) and when either clicking on the notification or on the application in the taskbar **sometimes** the application just closes. 

**To Reproduce**
Just focus on the application when there is a notification that needs to be checked. It may crash, but it's not a given.

**Desktop:**
 - OS: Debian Testing
 - Desktop Environment: Gnome on Wayland
 - Version: `GNOME Shell 44.5`

**Additional context**
Tutanota is installed as a flatpak application. I tried to launch the app from the terminal, hoping to come back to you with a clear error. Unfortunately there seems to be a lot of noise, so I can't really tell if my logs show anything useful (but I doubt).
I have attached them here as they don't contain anything sensitive.
[tutanotaLogs.log](https://github.com/tutao/tutanota/files/12929371/tutanotaLogs.log)

**Comment by LaPeste** [comment]
Just got context, the [issue](https://github.com/tutao/tutanota/issues/5998) was initially reported on the normal GH issue page. But then I was advice to open the issue here as it seemed to concern flatpak.

**Comment by LaPeste** [comment]
If it is of any help, I captured the logs from the terminal when a crash happens.
[tutanotaLogs.log](https://github.com/flathub/com.tutanota.Tutanota/files/13298843/tutanotaLogs.log)

**Comment by LaPeste** [comment]
Does this mean that the issue is acknowledged by the team?

**Comment by charlag** [comment]
We are aware of it but I am not sure what we can do at this point, I don't think any of our code is causing this and I think our best bet right now is Electron updates

**Comment by sohmahmood** [comment]
Just coming here to say I am getting the same issue after recently moving to Flatpack. @LaPeste where did you find the tutanota logs? I would like to see what is crashing the app.

I suspect it might have something to do with being minimized to the system tray.

My environment:
```
OS: Debian 12 bookworm
Kernel: x86_64 Linux 6.1.0-14-amd64
Desktop Environment: GNOME 43.6
Display Server: X11
Flatpack Version: 1.14.4
Tuta (com.tutanota.Tutanota) Version:  3.119.3
```

**Comment by LaPeste** [comment]
@smahm006 just run the application in the terminal: `flatpak run com.tutanota.Tutanota`

**Comment by agreedSkiing** [comment]
Been noticing it also and the latest crash that happened to me was when i tried to open tuta from the system tray  
[tuta.log](https://github.com/flathub/com.tutanota.Tutanota/files/13878027/tuta.log)

**Comment by agreedSkiing** [comment]
New crash this time when having the window open all the time and swapping to the inbox as I received an email, the android app notification triggered me to check the inbox on my desktop and seems to have received the email before the flatpack app.
[run-2024-01-13T12:07:55+00:00.log](https://github.com/flathub/com.tutanota.Tutanota/files/13929028/run-2024-01-13T12.07.55%2B00.00.log)

**Comment by agreedSkiing** [comment]
The application seems to be more stable now after https://github.com/electron/electron/pull/41691

**Comment by charlag** [comment]
I will close this for now, feel free to open another one if it still happens.
If it's flatpak-specific, please file it under flathub repo
