### ISSUE TITLE
Wrong cursor

### ISSUE THREAD

**Issue by RaptaG** [flathub/com.tutanota.Tutanota#142]
It does not happen with other Flatpaks

![](https://github.com/flathub/com.tutanota.Tutanota/assets/77157639/3fe743fd-5e90-4e29-b673-f7c190a26e6b)

I use the Breeze Cursor (on KDE), but instead this one shows up

**Comment by olof-nord** [comment]
I think we have a solution for this here: https://github.com/flathub/org.signal.Signal/pull/412
You are running KDE with Wayland perhaps?

**Comment by RaptaG** [comment]
> You are running KDE with Wayland perhaps?

This true, yes.

**Comment by RaptaG** [comment]
Works correctly in the recent versions after enabling Desktop Intergration
