### ISSUE TITLE
Tutanota .desktop not launching

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.tutanota.Tutanota#18]
Using the [`com.tutanota.Tutanota.desktop`](https://github.com/flathub/com.tutanota.Tutanota/blob/master/com.tutanota.Tutanota.desktop) doesn't work.

When I run the EXEC line in the desktop .desktop in `~/.local/share/flatpak/exports/share/applications/com.tutanotaTutanota`, it gives me the following error:

```bash
$ flatpak run --branch=stable --arch=x86_64 --command=tutanota-desktop.sh --file-forwarding com.tutanota.Tutanota
bwrap: execvp tutanota-desktop.sh: No such file or directory
```

I tested again by creating another user, and it still didn't work.

**Comment by TheEvilSkeleton** [comment]
Found the fix. I removed the `.sh` in the .desktop and it seems to be working now. I'll MR soon.

**Comment by ThracianKnight1907** [comment]
I still have this issue. Was the fix included in the flatpak version from flathub, or will it come later?

**Comment by TheEvilSkeleton** [comment]
It was recently fixed https://github.com/flathub/com.tutanota.Tutanota/pull/19. We just have to wait a couple of hours for it to be available in Flathub.

If you want to launch it now, you can run `flatpak run com.tutanota.Tutanota`.

**Comment by charlag** [comment]
@TheEvilSkeleton don't we have to make another release for that

**Comment by TheEvilSkeleton** [comment]
No. I just got an update, and now it works.
