### ISSUE TITLE
Application gives error warning on startup

### ISSUE THREAD

**Issue by linuxosd** [flathub/com.tutanota.Tutanota#39]
Flatpak Tutanota application gives error messages on startup but can't send error report. Clicking on send error report reproduces the error report dropdown. See screenshots.
![Screenshot_20210427_071752](https://user-images.githubusercontent.com/81487885/116236003-85325500-a72c-11eb-8dbe-f294ff54b469.png)
![Screenshot_20210427_071928](https://user-images.githubusercontent.com/81487885/116236012-8794af00-a72c-11eb-82d8-e60c9c8c7cb0.png)

The application worked perfectly before the last update. The new update also forced me to install gnome-keyring which I don't want on my KDE Plasma system.

**Comment by charlag** [comment]
Do you see the error is stdout?

**Comment by linuxosd** [comment]
I don't understand the question "stdout", can you provide more details and clarification on what you're asking?

**Comment by linuxosd** [comment]
Terminal output running the flatpak:

`flatpak run com.tutanota.Tutanota
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/tutanota/tutanota-desktop --type=zygote
the monkey has been patched
version:   3.82.17
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
config up to date
Gtk-Message: 08:51:36.145: Failed to load module "canberra-gtk-module"
alarm storage initialized
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri)
libGL error: failed to load driver: amdgpu
startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: radeonsi
default mailto handler: false
[2021-04-29T12:51:36.231Z] unexpected error: ee [CryptoError]: invalid mac
    at /app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:1:414970
    at Object.aes256Decrypt (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:1:415310)
    at Object.aesDecryptObject (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:200504)
    at Object._getEncryptedVar (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:203890)
    at async Object.start (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:228671)
Webapp ready
no update info on disk, disabling updater.
/home/linuxosd/.var/app/com.tutanota.Tutanota/data/applications/tutanota-desktop.desktop does not exist, checking for permission to ask for permission...
`

**Comment by charlag** [comment]
Your device key does not match your config. Please try to delete one of them (config should be at /home/$USER/.var/app/com.tutanota.Tutanota/config)

**Comment by linuxosd** [comment]
There are many folders in the /config directory with many files and I can't find anything that is a device key. Can you be more specific?

**Comment by charlag** [comment]
conf.json is config. Device key stored in your keychain (you can check it with GNOME Passwords and Keys e.g.). They don't match so you should delete one of them.

**Comment by linuxosd** [comment]
I deleted the conf.json file and restarted the application, and it works fine now. Thank you.
