### ISSUE TITLE
Could not access secret storage

### ISSUE THREAD

**Issue by linuxosd** [flathub/com.tutanota.Tutanota#45]
Error box pops up on startup Tutanota flatpak desktop application on KDE Plasma desktop.

Terminal output:

flatpak run com.tutanota.Tutanota
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/tutanota/tutanota-desktop --type=zygote
the monkey has been patched
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
version:   3.84.0
Gtk-Message: 13:56:15.384: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:56:15.384: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
config up to date
scheduling to check sse in 1 seconds
startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: i965
default mailto handler: false

![secretstorage](https://user-images.githubusercontent.com/81487885/120024028-9802a880-bfbc-11eb-8cb2-2ac3be3cf90b.png)

Latest version 3.84.0

**Comment by charlag** [comment]
Yes, and it has FAQ link to explain why.
