### ISSUE TITLE
"The currently installed verison is too old and not supported any longer."

### ISSUE THREAD

**Issue by kolgza** [flathub/com.tutanota.Tutanota#6]
It appears that the current Flathub version of Tutanota is so out of date that logins are refused until it is updated.
![tuta](https://user-images.githubusercontent.com/46303203/67149407-e8f6da80-f278-11e9-89cc-0ecde9ac496b.png)

**Comment by TingPing** [comment]
@charlag Are you still maintaining this package?

**Comment by charlag** [comment]
@TingPing yes, we still do although the state we received it is was barely working and it didn't change since then because we didn't know how to solve #4 . Now we don but we will wait for https://github.com/tutao/tutanota/pull/1521 because current build monkey-patches the build script and we would like to change that together with other build-system changes.
In short. the flatpak build doesn't work now. Maybe it should be pulled form Flathub temporarily and then put back when issues are resolved.

**Comment by TingPing** [comment]
#4 doesn't sound like that big of a blocker...

Anyway if you want to mark this package as end-of-life (it will be hidden in various places and warn users who install it) you can do so: https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

**Comment by charlag** [comment]
It doesn't seem so until the second window you open is blank. And the third one. Even after closing the first one.

I don't think it makes sense to mark it as end-of-life if we will fix it in a few weeks but thanks for letting me know.

**Comment by PopeRigby** [comment]
What's the progress on this?

**Comment by BuggStream** [comment]
> What's the progress on this?

I got an update here: https://github.com/tutao/tutanota/pull/1521#issuecomment-572512787

**Comment by charlag** [comment]
We are getting close with @ganthern working on unpacked build and disabled autoupdater (so that Flatpak build script doesn't have to patch anything in a hacky manner). Rollup migration is not necessary for Flatpak build then (which is still indefinitely postponed)

**Comment by BuggStream** [comment]
> We are getting close with @ganthern working on unpacked build and disabled autoupdater (so that Flatpak build script doesn't have to patch anything in a hacky manner). Rollup migration is not necessary for Flatpak build then (which is still indefinitely postponed)

So the rollup migration is postponed, but the flatpak build is on its way since it doesn't necessarily require rollup? If that's the case, it is good news!

**Comment by charlag** [comment]
That's correct, we just need to get required options into our build to not have constant patch conflicts. Unpacked build is one of them.

**Comment by atkka** [comment]
Still broken, what's the status on this?

**Comment by TheEvilSkeleton** [comment]
> Still broken, what's the status on this?

No status. It will remain broken for a while

**Comment by TheEvilSkeleton** [comment]
UPDATE NOW! https://github.com/flathub/com.tutanota.Tutanota/pull/15

(Also, sorry for being too pessimistic)
