### ISSUE TITLE
Enable wayland support

### ISSUE THREAD

**Issue by der-eismann** [flathub/com.tutanota.Tutanota#69]
Tutanota currently uses Electron 16, which has pretty solid Wayland support. All I needed to do was to add 
```
 --enable-features=UseOzonePlatform --ozone-platform=wayland
```
to the command. Maybe we could include a [wrapper script](https://github.com/flathub/org.signal.Signal/blob/master/signal-desktop.sh#L5-L8) like Signal did?

**Comment by charlag** [comment]
@der-eismann first time I see this flag, can you send some docs or reference? It's a Chromium switch if I understand correctly

**Comment by der-eismann** [comment]
Exactly, it's from Chromium. You can see it in the browser at chrome://flags/#ozone-platform-hint.
I'm not really sure what kind of docs or reference you expect.. somehow I can only find the flags themselves, e.g. at the [Arch wiki](https://wiki.archlinux.org/title/wayland#Electron). It has been supported since Electron 12, but I can't find much documentation.

**Comment by charlag** [comment]
@der-eismann it might be better to not fix it in Flatpak then but for us to always use it

**Comment by BirdInFire** [comment]
> @der-eismann it might be better to not fix it in Flatpak then but for us to always use it

+1 to fix this problem, because Wayland is the default on more and more desktop, XWayland isn't good for battery in laptop.

**Comment by BirdInFire** [comment]
> Tutanota currently uses Electron 16, which has pretty solid Wayland support. All I needed to do was to add
> 
> ```
>  --enable-features=UseOzonePlatform --ozone-platform=wayland
> ```
> 
> to the command. Maybe we could include a [wrapper script](https://github.com/flathub/org.signal.Signal/blob/master/signal-desktop.sh#L5-L8) like Signal did?

From the last version the '--enable-features=UseOzonePlatform' isn't needed anymore only '--ozone-platform=wayland' do work

**Comment by aalhitennf** [comment]
Would like to see this

**Comment by crepererum** [comment]
There are a few actual advantages under Wayland:

- **Security:** Keystrokes can no longer be read by any application.
- **Fractional Scaling:** Fractional scaling XWayland apps often results in blurry results while Wayland-native apps mostly seem to stay sharp.

**Comment by charlag** [comment]
Please send a PR and we will happily merge it in

**Comment by pm4rcin** [comment]
There are 2 options to enable wayland. The way Signal flatpak did which just adds env variable for wayland users to change. Or another way like [Fluent Reader flatpak](https://github.com/flathub/me.hyliu.fluentreader/commit/9be863dc55b10abacf72a8ad20690a3e8f9f4a47#) did which launches Wayland or X11 depending on if it's launched under wayland or X11. It detects environment automatically and launches so there's no need for end users to change anything via cli or flatseal. @charlag which one do you preffer?

**Comment by charlag** [comment]
I see no reason to not go with automatic approach at the moment.

**Comment by pm4rcin** [comment]
It'd be nice if someone could test flatpak from my [my PR](https://github.com/flathub/com.tutanota.Tutanota/pull/131#issuecomment-1719985669) on GNOME because Wayland Window decorations should be enabled by default in electron 26 and work out of the box.

**Comment by crepererum** [comment]
> It'd be nice if someone could test flatpak from my [my PR](https://github.com/flathub/com.tutanota.Tutanota/pull/131#issuecomment-1719985669) on GNOME because Wayland Window decorations should be enabled by default in electron 26 and work out of the box.

I'm runnig Gnome 44 (Arch Linux) and I confirm that:

- window decoration are present
- it's running on wayland:
  - indirect check using `xwininfo -tree -root` which lists tutanota on current "main" and does NOT list it anymore when using the test build)
  - indirect by "visual check", the window looks sharp even under fractional scaling now\\

Thank you :)

**Comment by pm4rcin** [comment]
@charlag would you merge PR?

**Comment by charlag** [comment]
I'll try to check it in the next days, thank you a lot for the PR!

**Comment by pm4rcin** [comment]
@charlag what has happened that you've reverted changes?

**Comment by charlag** [comment]
It got automatically reverted because we had to change manifest-template.js instead I suspect. I'll patch it back.

**Comment by pm4rcin** [comment]
> It got automatically reverted because we had to change manifest-template.js instead I suspect. I'll patch it back.

I see that you have patched but you haven't changed permisions like I did in my PR. Or maybe there's something I'm not aware of.
