### ISSUE TITLE
Error: invalid mac

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.tutanota.Tutanota#72]
Today I updated to latest flatpak version of Tutanota client and got this the following error when I'm trying to log in:
```
Feedback v3.91.9 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.91.9
 Timestamp (UTC): Mon, 07 Feb 2022 19:52:19 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.9 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
 Error message: invalid mac
Stacktrace: 
Error: invalid mac
    at os (file:///app/lib/tutanota/resources/app.asar/worker.js:1:38652)
    at Wu.decrypt (file:///app/lib/tutanota/resources/app.asar/worker.js:12:130667)
    at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:5590
    at C.handleMessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:7598)
    at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6851
    at _worker.onmessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6431)
```

I tried to log in using web interface and it worked, so the issue seems to be only in the desktop client itself.

**Comment by sofiageo** [comment]
Same error for me, I've stopped using the desktop client for a while now but I tried to login just now and I get the same error.

**Comment by charlag** [comment]
Your key in keychain doesn't match your stored credentials. You need to delete either the key or the data

**Comment by Zlopez** [comment]
I'm not able to even delete the existing credentials on the client. I got the same error.

When I tried to login again with my account, I just got `An error occured.`

**Comment by charlag** [comment]
It will not let you delete them because it cannot close session associated with them. You would need to manually delete user data (in `~/.config/tutanota-desktop`).

Any ideas how this might have happened? Did you use non-Flatpak version as well? Did push notifications work for you before?

I've also created issue in the main repo:
https://github.com/tutao/tutanota/issues/3875

**Comment by Zlopez** [comment]
What helped was to delete `~/.var/app/com.tutanota.Tutanota`. After deleting this folder I was able to log in again.

**Comment by Zlopez** [comment]
@charlag This happened after update to latest Tutanota flatpak. After update I wasn't able to log in, otherwise I'm logged in automatically.

**Comment by pizzadude** [comment]
After deleting ~/.var/app/com.tutanota.Tutanota and ~/.config/tutanota-desktop, I log in again, and then quit tutanota. Upon the next launch, the flatpak hangs on login, and I need to kill the process. Then I launch it again, and I get the 'invalid mac' error.

**Comment by charlag** [comment]
Tracking issue here now:
[#3875](https://github.com/tutao/tutanota/issues/3875)
