### ISSUE TITLE
Additional Permissions

### ISSUE THREAD

**Issue by qsyntrax** [flathub/com.tutanota.Tutanota#79]
![image](https://user-images.githubusercontent.com/96214827/153744795-c13b782b-806f-437b-a776-8c56fe3a125f.png)
Gnome software says there are additional permissions now.
Why where these added?
Thanks

**Comment by bedhub** [comment]
Hi @qsyntrax 
We are storing the key for the saved credentials in the keychain now and therefore we need these permissions. 

 https://github.com/tutao/tutanota/issues/3733
