### ISSUE TITLE
U2F and FIDO2 keys don't work in Tutanota Desktop

### ISSUE THREAD

**Issue by realpixelcode** [flathub/com.tutanota.Tutanota#90]
When logging in, one is asked to enter the OTP code or insert one of the registered security keys. However, the latter doesn't work in the desktop client (although it works perfectly fine in the browser) which I got from the Zorin Store.

In particular, I've got a Nitrokey U2F and a Nitrokey FIDO2 stick which are both registered with my Tutanota account and work fine in Tutanota's browser login.

1. Open Tutanota desktop.
2. Enter user name + password
3. Click on Login
4. Click on the button that says “Click here to use security key”
5. Insert security key.
6. Nothing happens.

OS: Zorin OS (Ubuntu Ubuntu 20.04 LTS, Linux 5.13.0-40-generic)
Desktop Environment, if applicable (on Linux): GNOME Shell
Version: v3.95.4

https://github.com/tutao/tutanota/issues/4061

**Comment by realpixelcode** [comment]
Loggin in with U2F/FIDO2 keys also works fine in the AppImage version available at https://tutanota.com/#download.

**Comment by trafotin** [comment]
Did you try enabling --device=all? This might be needed for security keys.

**Comment by olof-nord** [comment]
I understand this is a feature which Flatpak does not offer through its sandboxing yet - here should be some more information. https://github.com/flatpak/xdg-desktop-portal/issues/989

**Comment by olof-nord** [comment]
Looking into this a second time, we might be able to support this by making use of the `--socket=pcsc` permission. This is for example used by [Chrome](https://github.com/flathub/com.google.Chrome/blob/master/com.google.Chrome.yaml#L19)  and [Thunderbird](https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.json#L33).

**Comment by pm4rcin** [comment]
@realpixelcode you can close it as #203 was merged.
