### ISSUE TITLE
Printing does not work even with cups enabled

### ISSUE THREAD

**Issue by sradigan** [flathub/com.tutanota.Tutanota#91]
The print dialog does not bring up my local printers though applications installed through the system package manager does.

![image](https://user-images.githubusercontent.com/6443966/166266425-8feaaae7-916b-4a70-b2a7-195627eefef4.png)

I tried enabling Printing via Flatseal and restarting but that did not work.

![image](https://user-images.githubusercontent.com/6443966/166266471-b3870701-cf2b-40eb-b9bf-3e9a8b35a5e8.png)

I found a related issue on firefox which installs a shared object for printing support.

https://github.com/flathub/org.mozilla.firefox.BaseApp/commit/c10a9fc883a4d079dbab957e026f96ce824a8a45

**Comment by olof-nord** [comment]
I would argue that one step towards solving this could be to provide that finish-args `--socket=cups` in the flatpak manifest.

https://docs.flatpak.org/en/latest/flatpak-command-reference.html

**Comment by charlag** [comment]
It somehow works for me?
![Screenshot from 2023-12-15 19-15-26](https://github.com/flathub/com.tutanota.Tutanota/assets/3099142/aed0f85d-b2e2-4fb1-bc03-1344424d2470)

**Comment by olof-nord** [comment]
@sradigan, do you mind re-testing with the latest version of the Flatpak? When I was reading about this, I understood there should be a built-in Portal for printing so that it works without any changes does check out. I just dont have any printer set up on my machine (yet), so I am not in the best situation to test this out.

**Comment by sradigan** [comment]
@olof-nord It looks like the latest version has this fixed up! I did run into the [secret storage issue over on the main repo](https://github.com/tutao/tutanota/issues/6265), but after running `flatpak run com.tutanota.Tutanota --password-store="gnome-libsecret"` I was able to test printing and it appears to be getting information from cups. Thanks for the fix!

**Comment by olof-nord** [comment]
Fantastic news, many thanks for following up @sradigan!
