### ISSUE TITLE
Question about update

### ISSUE THREAD

**Issue by BirdInFire** [flathub/com.tutanota.Tutanota#98]
is there any reason that flathub ignore some version and not other (for instance 3.96.12 & 3.96.13) are ignored and 3.96.11 have come nearly instantly.

Thanks for the info.

**Comment by charlag** [comment]
I do not understand the question. sorry

**Comment by BirdInFire** [comment]
> I do not understand the question. sorry

i Do want to know if the update flathub side is automated, because some time tutanota on flathub isn't updated for one version (for exemple here the 3 last version we have updated from 3.96.11 to 3.96.13, 3.96.12 was bypassed) it's to see if there is rules in the update i do not know or if it's manually updated by flathub thats the question

**Comment by charlag** [comment]
There was no .12 flatpak release
Please check documentation for the software you use to consume flatpaks. This is not the best place to ask general flatpak questions.

**Comment by BirdInFire** [comment]
> There was no .12 flatpak release Please check documentation for the software you use to consume flatpaks. This is not the best place to ask general flatpak questions.

it seem you haven't read my question ...... you answer to why update aren't always do (i do tell they wasn't .12 as explaination of my question and you answer they wasn't .12) sériously don't answer to question if you answer something who don't have any thing to do to the question ............
